name: Build Darwin AMD64

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.7"

      - name: Set env vars
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="v0.0.0-${GITHUB_SHA::8}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and Package for Darwin
        run: |
          make install
          mv build/opinitd build/opinitd.arm64
          GOARCH=amd64 make install
          mv build/opinitd build/opinitd.amd64
          lipo -create -output build/opinitd  build/opinitd.arm64 build/opinitd.amd64
          tar -czf "$GITHUB_WORKSPACE"/opinitd_"$VERSION"_Darwin.tar.gz build/opinitd
          rm build/opinitd.arm64 build/opinitd.amd64 build/opinitd

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            opinitd_${{ env.VERSION }}_Darwin.tar.gz
        env:
          VERSION: ${{ env.VERSION }}
