name: Build executable binaries and release them

on:
  push:
    tags:
      - 'v*'
      - 'test-'
  
jobs:
  release-darwin:
    uses: ./.github/workflows/build-darwin.yml
  release-linux:
    uses: ./.github/workflows/build-linux.yml
